name: Build and Push to DigitalOcean on Main

on:
  push:
    branches:
      - main

jobs:
  build-push-chrome:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build the base layer
        run: docker build -f ./docker/base/Dockerfile -t ghcr.io/browserless/base:latest .

      - name: Build the Chrome image
        run: docker build --build-arg VERSION=latest -f ./docker/chrome/Dockerfile -t ghcr.io/browserless/chrome:latest .

      - name: Test the Chrome image
        run: docker run --ipc=host -e CI=true --entrypoint ./scripts/test.sh ghcr.io/browserless/chrome:latest

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
          password: ${{ secrets.VULTR_REGISTRY_PASSWORD }}

      - name: Tag Chrome image for DigitalOcean
        run: docker tag ghcr.io/browserless/chrome:latest registry.digitalocean.com/tnx-img/browserless-chrome:latest

      - name: Push to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/tnx-img/browserless-chrome:latest

  build-push-chromium:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build the base layer
        run: docker build -f ./docker/base/Dockerfile -t ghcr.io/browserless/base:latest .

      - name: Build the Chromium image
        run: docker build --build-arg VERSION=latest -f ./docker/chromium/Dockerfile -t ghcr.io/browserless/chromium:latest .

      - name: Test the Chromium image
        run: docker run --ipc=host -e CI=true --entrypoint ./scripts/test.sh ghcr.io/browserless/chromium:latest

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
          password: ${{ secrets.VULTR_REGISTRY_PASSWORD }}

      - name: Tag Chromium image for DigitalOcean
        run: docker tag ghcr.io/browserless/chromium:latest registry.digitalocean.com/tnx-img/browserless-chromium:latest

      - name: Push to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/tnx-img/browserless-chromium:latest
